import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CombineLayout } from "@/components/index";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Follow Up Master",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="relative flex size-full min-h-screen flex-col bg-[#111814] dark group/design-root overflow-x-hidden"
          // style="font-family: Inter, 'Noto Sans', sans-serif"
        >
          <CombineLayout>
            {children}
          </CombineLayout>
        </div>
      </body>
    </html>
  );
}
